# Generated by Django 5.2.5 on 2025-08-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isPrompt',
            field=models.BooleanField(default=True),
        ),
    ]
