# Generated by Django 5.2.5 on 2025-08-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_isprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hasMermaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='mermaid',
            field=models.TextField(default=''),
        ),
    ]
